<?php
// $Id$
/**
 * Implementation of hook_install().
 */
function chemistry_lab_install()
  {
    // Create tables.
    drupal_install_schema('chemistry_lab');
    variable_set('chemistry_lab_emails', '');
    variable_set('chemistry_lab_from_email', '');
    variable_set('chemistry_lab_abstract_upload_extensions', '');
    variable_set('chemistry_lab_report_upload_extensions', '');
    variable_set('chemistry_lab_code_files_extensions', '');
    // create uploads folder
    $upload_path = $_SERVER['DOCUMENT_ROOT'] . base_path() . 'soul_uploads/chemistry_lab_uploads/';
    if (!is_dir($upload_path))
        mkdir($upload_path);
    if (!is_dir($upload_path . '/latex'))
        mkdir($upload_path . '/latex');
    if (!is_dir($upload_path . '/DEPENDENCIES'))
        mkdir($upload_path . '/DEPENDENCIES');
  }
/**
 * Implementation of hook_uninstall().
 */
function chemistry_lab_uninstall()
  {
    // Remove tables.
    drupal_uninstall_schema('chemistry_lab');
    // Remove variables
    variable_del('chemistry_lab_emails');
    variable_del('chemistry_lab_from_email');
    variable_del('chemistry_lab_abstract_upload_extensions');
    variable_del('chemistry_lab_report_upload_extensions');
    variable_del('chemistry_lab_code_files_extensions');
  }
/**
 * Implementation of hook_schema().
 */

function chemistry_lab_schema()
 {
  /*proposal*/
  $schema['soul_chemistry_lab_proposal'] = array(
    'description' => t('TODO: please describe this table!'),
        'fields' => array(
          'id' => array(
          'description' => t('TODO: please describe this field!'),
                'type' => 'serial',
                'not null' => TRUE
            ),
          'uid' => array(
            'description' => t('TODO: please describe this field'),
                'type' => 'int', 
                'not null' => TRUE
            ),
          'approver_uid' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'not null' => TRUE
            ),
          'name_title' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '5',
                'not null' => TRUE
            ),
          'contributor_name' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '255',
                'not null' => TRUE
            ),
          'contact_no' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '15',
                'not null' => TRUE
            ),
          'university' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'text',
                'not null' => TRUE
            ),
          'department' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'text',
                'not null' => TRUE
            ),
          'city' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '100',
                'not null' => TRUE
            ),
          'pincode' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '10',
                'not null' => TRUE
            ),
          'state' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '100',
                'default value' => 'NONE',
                'not null' => TRUE
            ), 
          'country' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '100',
                'default value' => 'NONE',
                'not null' => TRUE
            ),  
          'options' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '200',
                'not null' => TRUE
            ), 
          'project_guide_name' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '255',
                'not null' => TRUE
            ),
          'project_guide_department' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'text',
                'not null' => TRUE
            ),
          'project_guide_email_id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '255',
                'default value' => 'NULL',
                'not null' => TRUE
            ),
          'project_title' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '255',
                'not null' => TRUE
            ),
          'description' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'text',
                'not null' => TRUE
            ),
          'software_version' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '50',
                'not null' => TRUE
            ),
          'directory_name' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '255',
                'not null' => TRUE
            ),
          'approval_status' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
          'is_submitted' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
          'is_completed' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'default value' => '0',
                'not null' => TRUE
            ),
          'dissapproval_reason' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'text',
                'not null' => TRUE
            ),
          'creation_date' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
          'approval_date' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
          'form_key' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '500',
                'not null' => TRUE
            ),
          'actual_completion_date' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'default value' => '0',
                'not null' => TRUE
            ),
          'samplefilepath' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'text',
                'not null' => TRUE
            ),
            ),
          'reference' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'text',
                'not null' => TRUE
            ),
          'fellowship' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '10',
                'not null' => TRUE
            ),
          'expected_date_of_completion' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
          ),
        'primary key' => array(
            'id'
        )
    );
    /* experiment */
    $schema['soul_chemistry_lab_experiment'] = array(
        'description' => t('TODO: please describe this table!'),
        'fields' => array(
            'id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'serial',
                'not null' => TRUE
            ),
            'proposal_id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'number' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'title' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '500',
                'not null' => TRUE
            )
            'description' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '1000',
                'not null' => TRUE
            )
        ),
        'primary key' => array(
            'id'
        )
    );
    /* solution */
    $schema['soul_chemistry_lab_solution'] = array(
        'description' => t('TODO: please describe this table!'),
        'fields' => array(
            'id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'serial',
                'not null' => TRUE
            ),
            'experiment_id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'approver_uid' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'code_number' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '10',
                'not null' => TRUE
            ),
            'caption' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '255',
                'not null' => TRUE
            ),
            'approval_date' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'approval_status' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'timestamp' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            )
            'os_used' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '50',
                'not null' => TRUE
            ),
            'soul_version' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '20',
                'not null' => TRUE
            ),
            'toolbox_used' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '100',
                'not null' => TRUE
            ),
        ),
        'primary key' => array(
            'id'
        )
    );
    /* solution files */
    $schema['soul_chemistry_lab_solution_files'] = array(
        'description' => t('TODO: please describe this table!'),
        'fields' => array(
            'id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'serial',
                'not null' => TRUE
            ),
            'solution_id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'filename' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '255',
                'not null' => TRUE
            ),
            'filepath' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '500',
                'not null' => TRUE
            ),
            'pdfpath' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '500',
                'default value' => 'None',
                'not null' => TRUE
            ),
            'filemime' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '255',
                'not null' => TRUE
            ),
            'filesize' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'filetype' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '1',
                'not null' => TRUE
            ),
            'caption' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '100',
                'not null' => TRUE
            ),
            'timestamp' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            )
        ),
        'primary key' => array(
            'id'
        )
    );
    /* dependency files - links */
    $schema['soul_chemistry_lab_solution_dependency'] = array(
        'description' => t('TODO: please describe this table!'),
        'fields' => array(
            'id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'serial',
                'not null' => TRUE
            ),
            'solution_id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'dependency_id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            )
        ),
        'primary key' => array(
            'id'
        )
    );
    /* depedency files */
    $schema['soul_chemistry_lab_solution_dependency_files'] = array(
        'description' => t('TODO: please describe this table!'),
        'fields' => array(
            'id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'serial',
                'not null' => TRUE
            ),
            'proposal_id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'filename' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '255',
                'not null' => TRUE
            ),
            'filepath' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '500',
                'not null' => TRUE
            ),
            'filemime' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '255',
                'not null' => TRUE
            ),
            'filesize' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'caption' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '100',
                'not null' => TRUE
            ),
            'description' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'text',
                'size' => 'medium',
                'not null' => TRUE
            ),
            'timestamp' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            )
        ),
        'primary key' => array(
            'id'
        )
    );
    /* qr_code */
    $schema['soul_chemistry_lab_qr_code'] = array(
        'description' => t('TODO: please describe this table!'),
        'fields' => array(
            'id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'serial',
                'not null' => TRUE
            ),
            'proposal_id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'qr_code' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'size' => '10',
                'not null' => TRUE
            )
        ),
        'primary key' => array(
            'id'
        )
    );
     /* submitted_abstracts */
    $schema['soul_chemistry_lab_submitted_abstracts'] = array(
        'description' => t('TODO: please describe this table!'),
        'fields' => array(
            'id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'serial',
                'not null' => TRUE
            ),
            'proposal_id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'approver_uid' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'abstract_approval_status' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'abstract_upload_date' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'abstract_approval_date' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'is_submitted' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
        ),
        'primary key' => array(
            'id'
        )
    );
    /* submitted_abstracts_file */
    $schema['soul_chemistry_lab_submitted_abstracts_file'] = array(
        'description' => t('TODO: please describe this table!'),
        'fields' => array(
            'id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'serial',
                'not null' => TRUE
            ),
            'submitted_abstract_id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'proposal_id' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'uid' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'approvar_uid' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            ),
            'filename' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '1000',
                'not null' => TRUE
            ),
            'filepath' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '1000',
                'not null' => TRUE
            ),
            'filemime' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '1000',
                'not null' => TRUE
            ),
            'filesize' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '1000',
                'not null' => TRUE
            ),
            'filetype' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'varchar',
                'length' => '1000',
                'not null' => TRUE
            ),
            'timestamp' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            )
            'file_approval_status' => array(
                'description' => t('TODO: please describe this field!'),
                'type' => 'int',
                'length' => '11',
                'not null' => TRUE
            )
        ),
        'primary key' => array(
            'id'
        )
    );
    return $schema;
  }