<?php
// $Id$
require_once('general_deletion.inc');
require_once('email.inc');
/**
 * Implementation of hook_menu().
 */
function chemistry_lab_menu()
{
	$items = array();
	/* PROPOSAL */
	$items['chemistry-lab-project/proposal'] = array(
		'title' => 'Chemistry Lab Proposal Form',
		'description' => 'Chemistry Lab Proposal Form',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'chemistry_lab_proposal_form'
		),
		'access arguments' => array(
			'soul chemistry lab create proposal'
		),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'proposal.inc'
	);
	$items['chemistry-lab-project/manage-proposal'] = array(
		'title' => 'Manage Chemistry Lab Proposals',
		'description' => 'Manage Chemistry Lab Proposals',
		'page callback' => 'chemistry_lab_proposal_pending',
		'access callback' => 'user_access',
		'access arguments' => array(
			'soul chemistry lab manage proposal'
		),
		'file' => 'manage_proposal.inc'
	);
	$items['chemistry-lab-project/manage-proposal/pending'] = array(
		'title' => 'Pending Proposals',
		'description' => 'Pending soul chemistry lab Proposals Queue',
		'page callback' => 'chemistry_lab_proposal_pending',
		'access callback' => 'user_access',
		'access arguments' => array(
			'soul chemistry lab manage proposal'
		),
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => 1,
		'file' => 'manage_proposal.inc'
	);
	$items['chemistry-lab-project/manage-proposal/all'] = array(
		'title' => 'All Proposals',
		'description' => 'All Proposals',
		'page callback' => 'chemistry_lab_proposal_all',
		'access callback' => 'user_access',
		'access arguments' => array(
			'soul chemistry lab manage proposal'
		),
		'type' => MENU_LOCAL_TASK,
		'weight' => 4,
		'file' => 'manage_proposal.inc'
	);
	$items['chemistry-lab-project/manage-proposal/approve'] = array(
		'title' => 'Approve Proposal',
		'description' => 'Approve Proposal',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'chemistry_lab_proposal_approval_form'
		),
		'access arguments' => array(
			'soul chemistry lab manage proposal'
		),
		'type' => MENU_CALLBACK,
		'file' => 'manage_proposal.inc'
	);
	$items['chemistry-lab-project/manage-proposal/solution-proposal-approve'] = array(
		'title' => 'Approve Solution Proposal',
		'description' => 'Approve Solution Proposal',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'chemistry_lab_solution_proposal_approval_form'
		),
		'access arguments' => array(
			'soul chemistry lab manage proposal'
		),
		'type' => MENU_CALLBACK,
		'file' => 'manage_solution_proposal.inc'
	);
	$items['chemistry-lab-project/manage-proposal/edit'] = array(
		'title' => 'Edit Proposal',
		'description' => 'Edit Proposal',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'chemistry_lab_proposal_edit_form'
		),
		'access arguments' => array(
			'soul chemistry lab manage proposal'
		),
		'type' => MENU_CALLBACK,
		'file' => 'manage_proposal.inc'
	);
	$items['chemistry-lab-project/manage-proposal/status'] = array(
		'title' => 'Proposal Status',
		'description' => 'Proposal Status',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'chemistry_lab_proposal_status_form'
		),
		'access arguments' => array(
			'soul chemistry lab approve proposal'
		),
		'type' => MENU_CALLBACK,
		'file' => 'manage_proposal.inc'
	);
	$items['chemistry-lab-project/show-proposal'] = array(
		'title' => 'soul chemistry lab Solution Proposal',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'chemistry_lab_solution_proposal_form'
		),
		'access arguments' => array(
			'soul chemistry lab propose solution'
		),
		'type' => MENU_CALLBACK,
		'file' => 'solution_proposal.inc'
	);
	/* CODE REVIEW */
	$items['chemistry-lab-project/code-approval'] = array(
		'title' => 'Manage Code Approval',
		'description' => 'Manage Code Approval',
		'page callback' => 'chemistry_lab_abstract_approval',
		'access arguments' => array(
			'soul chemistry lab approve code'
		),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'abstract_approval.inc'
	);
	$items['chemistry-lab-project/abstract-approval/approve'] = array(
		'title' => 'Code Approval',
		'description' => 'Code Approval',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'chemistry_lab_abstract_approval_form'
		),
		'access arguments' => array(
			'soul chemistry lab approve code'
		),
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => 1,
		'file' => 'abstract_approval.inc'
	);
	$items['chemistry-lab-project/abstract-approval/bulk'] = array(
		'title' => 'Bulk Manage',
		'description' => 'Bulk Mangage',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'chemistry_lab_abstract_bulk_approval_form'
		),
		'access arguments' => array(
			'soul chemistry lab bulk manage abstract'
		),
		'type' => MENU_LOCAL_TASK,
		'weight' => 2,
		'file' => 'abstract_bulk_approval.inc'
	);
	$items['chemistry-lab-project/code-approval/bulk'] = array(
		'title' => 'Bulk Manage',
		'description' => 'Bulk Mangage',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'chemistry_lab_bulk_approval_form'
		),
		'access arguments' => array(
			'soul chemistry lab bulk manage abstract'
		),
		'type' => MENU_LOCAL_TASK,
		'weight' => 2,
		'file' => 'bulk_approval.inc'
	);
	/*$items['chemistry_lab/code_approval/dependency'] = array(
	'title' => 'Dependency',
	'description' => 'Dependency Mangage',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('chemistry_lab_dependency_approval_form'),
	'access arguments' => array('soul chemistry lab bulk manage abstract'),
	'type' => MENU_LOCAL_TASK,
	'weight' => 3,
	'file' => 'dependency_approval.inc',
	);*/
	$items['chemistry-lab-project/code-approval/upload'] = array(
		'title' => 'Upload Code',
		'description' => 'Admin Upload',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'chemistry_lab_bulk_upload_code_form'
		),
		'access arguments' => array(
			'soul chemistry lab bulk manage abstract'
		),
		'type' => MENU_CALLBACK,
		'weight' => 4,
		'file' => 'bulk_upload_code.inc'
	);
	$items['chemistry-lab-project/code-approval/notes'] = array(
		'title' => 'Notes for Reviewers',
		'description' => 'Notes for Reviewers',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'chemistry_lab_lab_notes_form'
		),
		'access arguments' => array(
			'soul chemistry lab bulk manage abstract'
		),
		'type' => MENU_CALLBACK,
		'weight' => 4,
		'file' => 'notes.inc'
	);
	/* CODE UPLOAD */
	$items['chemistry-lab-project/abstract-code'] = array(
		'title' => 'Abstract and Project Files Upload',
		'description' => 'Abstract Submission',
		'page callback' => 'chemistry_lab_abstract',
		'access callback' => 'user_access',
		'access arguments' => array(
			'soul chemistry lab upload abstract'
		),
		'file' => 'upload_code.inc'
	);
	$items['chemistry-lab-project/abstract-code/chemistry-lab-project-list'] = array(
		'title' => 'chemistry lab',
		'description' => 'List Experiments',
		'page callback' => 'chemistry_lab_abstract',
		'access arguments' => array(
			'soul chemistry lab upload abstract'
		),
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'file' => 'upload_code.inc',
		'weight' => 1
	);
	$items['chemistry-lab-project/abstract-code/upload'] = array(
		'title' => 'Abstract and Project Upload',
		'description' => 'Project Upload',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'chemistry_lab_upload_abstract_code_form'
		),
		'access arguments' => array(
			'soul chemistry lab upload abstract'
		),
		'type' => MENU_LOCAL_TASK,
		'file' => 'upload_code.inc',
		'weight' => 2
	);
	$items['chemistry-lab-project/abstract-code/delete'] = array(
		'title' => 'Delete Solution',
		'description' => 'Delete Solution',
		'page callback' => 'chemistry_lab_upload_code_delete',
		'access arguments' => array(
			'soul chemistry lab upload code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'upload_code_delete.inc'
	);
	/* CODE DOWNLOADS */
	$items['chemistry-lab-project/download/file'] = array(
		'title' => 'Code Download',
		'description' => 'Code Download',
		'page callback' => 'chemistry_lab_download_solution_file',
		'access arguments' => array(
			'soul chemistry lab download code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'download.inc'
	);
	$items['chemistry-lab-project/download/solution'] = array(
		'title' => 'Code Download',
		'description' => 'Code Download',
		'page callback' => 'chemistry_lab_download_solution',
		'access arguments' => array(
			'soul chemistry lab download code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'download.inc'
	);
	$items['chemistry-lab-project/download/experiment'] = array(
		'title' => 'Code Download',
		'description' => 'Code Download',
		'page callback' => 'chemistry_lab_download_experiment',
		'access arguments' => array(
			'soul chemistry lab download code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'download.inc'
	);
	$items['chemistry-lab-project/download/lab'] = array(
		'title' => 'Code Download',
		'description' => 'Code Download',
		'page callback' => 'chemistry_lab_download_lab',
		'access arguments' => array(
			'soul chemistry lab download code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'download.inc'
	);
	$items['chemistry-lab-project/full-download/experiment'] = array(
		'title' => 'Code Download',
		'description' => 'Code Download',
		'page callback' => 'chemistry_lab_download_completed_project',
		'access arguments' => array(
			'soul chemistry lab approve code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'full_download.inc'
	);
	$items['chemistry-lab-project/full-download/project'] = array(
		'title' => 'Code Download',
		'description' => 'Code Download',
		'page callback' => 'chemistry_lab_download_full_project',
		'access arguments' => array(
			'soul chemistry lab download code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'full_download.inc'
	);
	/* COMPLETED soul chemistry labs */
	$items['chemistry-lab-project/completed-labs'] = array(
		'title' => 'Completed chemistry labs',
		'page callback' => 'chemistry_lab_completed_proposals_all',
		'access arguments' => array(
			'soul chemistry lab download code'
		),
		'file' => 'chemistry_lab_details.inc',
	);
	$items['chemistry-lab-project/completed-labs/simulations'] = array(
		'title' => 'Completed chemistry labs',
		'page callback' => 'chemistry_lab_completed_proposals_all',
		'access arguments' => array(
			'soul chemistry lab download code'
		),
		'file' => 'chemistry_lab_details.inc',
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => 0
	);
	/* LABS IN PROGRESS */
	$items['chemistry-lab-project/chemistry-lab-progress'] = array(
		'title' => 'chemistry labs in Progress',
		'page callback' => 'chemistry_lab_progress_all',
		'access arguments' => array(
			'soul chemistry lab download code'
		),
		'file' => 'chemistry_lab_details.inc'
	);
	/* DOWNLOAD FOR EVERYONE */
	$items['chemistry-lab-project/soul-chemistry-lab-run'] = array(
		'title' => 'Download Codes',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'chemistry_lab_run_form'
		),
		'access arguments' => array(
			'soul chemistry lab download code'
		),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'run.inc'
	);
	$items['chemistry-lab-project/download/abstract-file'] = array(
		'title' => 'Download user defined compound file',
		'description' => 'Download resource file',
		'page callback' => 'chemistry_lab_download_upload_file',
		'access arguments' => array(
			'soul chemistry lab download code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'download.inc'
	);
	$items['chemistry-lab-project/download/project-file'] = array(
		'title' => 'Download Project file',
		'description' => 'Download project file',
		'page callback' => 'soul_chemistry_lab_project_files',
		'access arguments' => array(
			'soul chemistry lab download code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'download.inc'
	);
	/* LATEX SCRIPT */
	$items['chemistry-lab-project/generate-lab'] = array(
		'title' => 'Generate Lab',
		'description' => 'Generate Lab From Latex Script',
		'page callback' => 'chemistry_lab_download_lab_pdf',
		'access arguments' => array(
			'soul chemistry lab generate lab'
		),
		'type' => MENU_CALLBACK,
		'file' => 'latex.inc'
	);
	$items['chemistry-lab-project/delete-lab'] = array(
		'title' => 'Delete Lab PDF',
		'description' => 'Delete Lab PDF',
		'page callback' => 'chemistry_lab_delete_lab_pdf',
		'access arguments' => array(
			'soul chemistry lab approve code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'latex.inc'
	);
	/* ADMIN SETTINGS */
	$items['admin/settings/soul-chemistry lab'] = array(
		'title' => 'soul chemistry lab Settings',
		'description' => 'soul chemistry lab Settings',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'chemistry_lab_settings_form'
		),
		'access arguments' => array(
			'administer soul chemistry lab'
		),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'settings.inc'
	);
	/* AJAX REQUEST */
	$items["lab-bulk-manage-exp/ajax"] = array(
		"title" => "Ajax callbacks",
		"page callback" => "lab_bulk_manage_exp_ajax",
		"access arguments" => array(
			"soul chemistry lab bulk manage abstract"
		),
		"type" => MENU_CALLBACK,
		'file' => 'bulk_approval.inc'
	);
	$items['chemistry-lab-project/certificates'] = array(
		'title' => 'List of chemistry lab Certificates',
		'description' => 'List of chemistry lab Certificates',
		'page callback' => '_list_chemistry_lab_certificates',
		'access arguments' => array(
			'list chemistry lab certificates'
		),
		'file' => 'pdf/list_chemistry_lab_certificate.inc'
	);
	$items['chemistry-lab-project/certificates/generate-pdf'] = array(
		'title' => 'Download Certificate',
		'description' => 'Download Certificate',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'generate_pdf'
		),
		'type' => MENU_CALLBACK,
		'access arguments' => array(
			'generate pdf'
		),
		'file' => 'pdf/cert_new.inc'
	);
	$items['chemistry-lab-project/certificates-custom'] = array(
		'title' => 'List of chemistry lab Custom Certificates',
		'description' => 'List of chemistry lab Custom Certificates',
		'page callback' => '_list_chemistry_lab_custom_certificates',
		'access arguments' => array(
			'list chemistry lab custom certificates'
		),
		'file' => 'pdf/list_mentor_certificates.inc'
	);
	$items['chemistry-lab-project/certificates-custom/pdf'] = array(
		'title' => 'Download Certificate',
		'description' => 'Download Certificate',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'generate_pdf'
		),
		'type' => MENU_CALLBACK,
		'access arguments' => array(
			'generate pdf'
		),
		'file' => 'pdf/mentor_cert_pdf.inc'
	);
	$items['chemistry-lab-project/certificates/verify'] = array(
		"title" => "Certificate Verification",
		"page callback" => "verify_certificates",
		'page arguments' => array(
			'verify_certificates'
		),
		"access arguments" => array(
			"verify certificates"
		),
		'type' => MENU_CALLBACK,
		'file' => 'pdf/verify_certificates.inc'
	);
	return $items;
}
/**
 * Implementation of hook_perm().
 */
function chemistry_lab_permission()
{
	return array(
		'soul chemistry lab create proposal' => array(
			'title' => t('soul chemistry lab create proposal'),
			'restrict access' => TRUE
		),
		'soul chemistry lab manage proposal' => array(
			'title' => t('soul chemistry lab manage proposal'),
			'restrict access' => TRUE
		),
		'soul chemistry lab edit proposal' => array(
			'title' => t('soul chemistry lab edit proposal'),
			'restrict access' => TRUE
		),
		'soul chemistry lab approve proposal' => array(
			'title' => t('soul chemistry lab approve proposal'),
			'restrict access' => TRUE
		),
		'soul chemistry lab propose solution' => array(
			'title' => t('soul chemistry lab propose solution'),
			'restrict access' => TRUE
		),
		'soul chemistry lab approve code' => array(
			'title' => t('soul chemistry lab approve code'),
			'restrict access' => TRUE
		),
		'soul chemistry lab bulk manage abstract' => array(
			'title' => t('soul chemistry lab bulk manage abstract'),
			'restrict access' => TRUE
		),
		'soul chemistry lab bulk delete abstract' => array(
			'title' => t('soul chemistry lab bulk delete code'),
			'restrict access' => TRUE
		),
		'soul chemistry lab upload abstract' => array(
			'title' => t('soul chemistry lab upload code'),
			'restrict access' => TRUE
		),
		'soul chemistry lab download code' => array(
			'title' => t('soul chemistry lab download code'),
			'restrict access' => TRUE
		),
		'administer soul chemistry lab' => array(
			'title' => t('administer soul chemistry lab'),
			'restrict access' => TRUE
		),
		'soul chemistry lab generate abstract' => array(
			'title' => t('soul chemistry lab generate abstract'),
			'restrict access' => TRUE
		),
		"list chemistry lab certificates" => array(
			"title" => t("list the certificates"),
			"description" => t("list the certificates"),
			'restrict access' => TRUE
		),
		"list chemistry lab custom certificates" => array(
			"title" => t("list the mentor certificates"),
			"description" => t("list the mentor certificates"),
			'restrict access' => TRUE
		),
		"verify certificates" => array(
			"title" => t("verify the certificates"),
			"description" => t("verify the certificates"),
			'restrict access' => TRUE
		)

	);
	// return array('soul chemistry lab create proposal', 'soul chemistry lab manage proposal', 'soul chemistry lab edit proposal', 'soul chemistry lab approve proposal', 'soul chemistry lab propose solution', 'soul chemistry lab approve code', 'soul chemistry lab bulk manage abstract', 'soul chemistry lab bulk delete code', 'soul chemistry lab upload code', 'soul chemistry lab download code', 'administer soul chemistry lab', 'soul chemistry lab generate lab');
}
/* AJAX CALLS */
/*function chemistry_lab_ajax()
{
	$query_type = arg(2);
	if ($query_type == 'chapter_title')
	{
		$chapter_number = arg(3);
		$preference_id = arg(4);
		//$chapter_q = db_query("SELECT * FROM {soul_chemistry_lab_chapter} WHERE number = %d AND preference_id = %d LIMIT 1", $chapter_number, $preference_id);
		$query = db_select('soul_chemistry_lab_chapter');
		$query->fields('soul_chemistry_lab_chapter');
		$query->condition('number', $chapter_number);
		$query->condition('preference_id', $preference_id);
		$query->range(0, 1);
		$chapter_q = $query->execute();
		if ($chapter_data = $chapter_q->fetchObject())
		{
			echo $chapter_data->name;
			return;
		} //$chapter_data = $chapter_q->fetchObject()
	} //$query_type == 'chapter_title'
	else if ($query_type == 'example_exists')
	{
		$chapter_number = arg(3);
		$preference_id = arg(4);
		$example_number = arg(5);
		$chapter_id = 0;
		$query = db_select('soul_chemistry_lab_chapter');
		$query->fields('soul_chemistry_lab_chapter');
		$query->condition('number', $chapter_number);
		$query->condition('preference_id', $preference_id);
		$query->range(0, 1);
		$chapter_q = $query->execute();
		if (!$chapter_data = $chapter_q->fetchObject())
		{
			echo '';
			return;
		} //!$chapter_data = $chapter_q->fetchObject()
		else
		{
			$chapter_id = $chapter_data->id;
		}
		$query = db_select('soul_chemistry_lab_example');
		$query->fields('soul_chemistry_lab_example');
		$query->condition('chapter_id', $chapter_id);
		$query->condition('number', $example_number);
		$query->range(0, 1);
		$example_q = $query->execute();
		if ($example_data = $example_q->fetchObject())
		{
			if ($example_data->approval_status == 1)
				echo 'Warning! Solution already approved. You cannot upload the same solution again.';
			else
				echo 'Warning! Solution already uploaded. Delete the solution and reupload it.';
			return;
		} //$example_data = $example_q->fetchObject()
	} //$query_type == 'example_exists'
	echo '';
}*/
/*************************** VALIDATION FUNCTIONS *****************************/
function chemistry_lab_check_valid_filename($file_name)
{
	if (!preg_match('/^[0-9a-zA-Z\.\_-]+$/', $file_name))
		return FALSE;
	else if (substr_count($file_name, ".") > 1)
		return FALSE;
	else
		return TRUE;
}
function chemistry_lab_check_name($name = '')
{
	if (!preg_match('/^[0-9a-zA-Z\ ]+$/', $name))
		return FALSE;
	else
		return TRUE;
}
function chemistry_lab_check_code_number($number = '')
{
	if (!preg_match('/^[0-9]+$/', $number))
		return FALSE;
	else
		return TRUE;
}
function chemistry_lab_path()
{
	return $_SERVER['DOCUMENT_ROOT'] . base_path() . 'soul_uploads/chemistry_lab_uploads/';
}
function chemistry_lab_file_path($value='')
{
	return $_SERVER['DOCUMENT_ROOT'] . base_path() . 'soul_uploads/';
}
/************************* USER VERIFICATION FUNCTIONS ************************/
function chemistry_lab_get_proposal()
{
	global $user;
	$query = db_select('soul_chemistry_lab_proposal');
	$query->fields('soul_chemistry_lab_proposal');
	$query->condition('uid', $user->uid);
	$query->orderBy('id', 'DESC');
	$query->range(0, 1);
	$proposal_q = $query->execute();
	$proposal_data = $proposal_q->fetchObject();
	if (!$proposal_data)
	{
		drupal_set_message("You do not have any approved soul chemistry lab proposal. Please propose the chemistry lab proposal", 'error');
		drupal_goto('');
	} //!$proposal_data
	switch ($proposal_data->approval_status)
	{
		case 0:
			drupal_set_message(t('Proposal is awaiting approval.'), 'status');
			return FALSE;
		case 1:
			return $proposal_data;
		case 2:
			drupal_set_message(t('Proposal has been dis-approved.'), 'error');
			return FALSE;
		case 3:
			drupal_set_message(t('Proposal has been marked as completed.'), 'status');
			return FALSE;
		default:
			drupal_set_message(t('Invalid proposal state. Please contact site administrator for further information.'), 'error');
			return FALSE;
	} //$proposal_data->approval_status
	return FALSE;
}
/*************************************************************************/
/***** Function To convert only first charater of string in uppercase ****/
/*************************************************************************/
function ucname($string)
{
	$string = ucwords(strtolower($string));
	foreach (array(
		'-',
		'\''
	) as $delimiter)
	{
		if (strpos($string, $delimiter) !== false)
		{
			$string = implode($delimiter, array_map('ucfirst', explode($delimiter, $string)));
		} //strpos($string, $delimiter) !== false
	} //array( '-', '\'' ) as $delimiter
	return $string;
}
function _df_sentence_case($string)
{
	$string = ucwords(strtolower($string));
	foreach (array(
		'-',
		'\''
	) as $delimiter)
	{
		if (strpos($string, $delimiter) !== false)
		{
			$string = implode($delimiter, array_map('ucfirst', explode($delimiter, $string)));
		} //strpos($string, $delimiter) !== false
	} //array( '-', '\'' ) as $delimiter
	return $string;
}
function _df_list_of_states()
{
	$states = array(
		0 => '-Select-'
	);
	$query = db_select('list_states_of_india');
	$query->fields('list_states_of_india');
	//$query->orderBy('', '');
	$states_list = $query->execute();
	while ($states_list_data = $states_list->fetchObject())
	{
		$states[$states_list_data->state] = $states_list_data->state;
	} //$states_list_data = $states_list->fetchObject()
	return $states;
}
function _df_list_of_cities()
{
	$city = array(
		0 => '-Select-'
	);
	$query = db_select('list_cities_of_india');
	$query->fields('list_cities_of_india');
	$query->orderBy('city', 'ASC');
	$city_list = $query->execute();
	while ($city_list_data = $city_list->fetchObject())
	{
		$city[$city_list_data->city] = $city_list_data->city;
	} //$city_list_data = $city_list->fetchObject()
	return $city;
}
function _df_list_of_pincodes()
{
	$pincode = array(
		0 => '-Select-'
	);
	$query = db_select('list_of_all_india_pincode');
	$query->fields('list_of_all_india_pincode');
	$query->orderBy('pincode', 'ASC');
	$pincode_list = $query->execute();
	while ($pincode_list_data = $pincode_list->fetchObject())
	{
		$pincode[$pincode_list_data->pincode] = $pincode_list_data->pincode;
	} //$pincode_list_data = $pincode_list->fetchObject()
	return $pincode;
}

function _df_list_of_departments()
{
	$department = array();
	$query = db_select('list_of_departments');
	$query->fields('list_of_departments');
	$query->orderBy('id', 'DESC');
	$department_list = $query->execute();
	while ($department_list_data = $department_list->fetchObject())
	{
		$department[$department_list_data->department] = $department_list_data->department;
	} //$department_list_data = $department_list->fetchObject()
	return $department;
}
function _df_dir_name($project, $proposar_name)
{
	$project_title = ucname($project);
	$proposar_name = ucname($proposar_name);
	$dir_name = $project_title . ' By ' . $proposar_name;
	$directory_name = str_replace("__", "_", str_replace(" ", "_", str_replace("/","_", trim($dir_name))));
	return $directory_name;
}
function chemistry_lab_document_path()
{
	return $_SERVER['DOCUMENT_ROOT'] . base_path() . 'soul_uploads/chemistry_lab_uploads/';
}
function DF_RenameDir($proposal_id, $dir_name)
{
	$proposal_id = $proposal_id;
	$dir_name = $dir_name;
	$query = db_query("SELECT directory_name,id FROM soul_chemistry_lab_proposal WHERE id = :proposal_id", array(
		':proposal_id' => $proposal_id
	));
	$result = $query->fetchObject();
	if ($result != NULL)
	{
		$files = scandir(chemistry_lab_path());
		$files_id_dir = chemistry_lab_path() . $result->id;
		//var_dump($files);die;
		$file_dir = chemistry_lab_path() . $result->directory_name;
		if (is_dir($file_dir))
		{
			$new_directory_name = rename(chemistry_lab_path() . $result->directory_name, chemistry_lab_path() . $dir_name);
			return $new_directory_name;
		} //is_dir($file_dir)
		else if (is_dir($files_id_dir))
		{
			$new_directory_name = rename(chemistry_lab_path() . $result->id, chemistry_lab_path() . $dir_name);
			return $new_directory_name;
		} //is_dir($files_id_dir)
		else
		{
			drupal_set_message('Directory not available for rename.');
			return;
		}
	} //$result != NULL
	else
	{
		drupal_set_message('Project directory name not present in databse');
		return;
	}
	return;
}
function CreateReadmeFileSoulchemistryLabProject($proposal_id)
{
	$result = db_query("
                        SELECT * from soul_chemistry_lab_proposal WHERE id = :proposal_id", array(
		":proposal_id" => $proposal_id
	));
	$proposal_data = $result->fetchObject();
	$root_path = chemistry_lab_path();
	$readme_file = fopen($root_path . $proposal_data->directory_name . "/README.txt", "w") or die("Unable to open file!");
	$txt = "";
	$txt .= "About the chemistry Lab";
	$txt .= "\n" . "\n";
	$txt .= "Title Of The chemistry Lab Project: " . $proposal_data->project_title . "\n";
	$txt .= "Proposar Name: " . $proposal_data->name_title . " " . $proposal_data->contributor_name . "\n";
	$txt .= "University: " . $proposal_data->university . "\n";
	$txt .= "\n" . "\n";
	$txt .= "soul chemistry lab Project By FOSSEE, IIT Bombay" . "\n";
	fwrite($readme_file, $txt);
	fclose($readme_file);
	return $txt;
}
function rrmdir_project($prop_id)
{
	$proposal_id = $prop_id;
	$result = db_query("
					SELECT * from soul_chemistry_lab_proposal WHERE id = :proposal_id", array(
		":proposal_id" => $proposal_id
	));
	$proposal_data = $result->fetchObject();
	$root_path = chemistry_lab_document_path();
	$dir = $root_path . $proposal_data->directory_name;
	if ($proposal_data->id == $prop_id)
	{
		if (is_dir($dir))
		{
			$objects = scandir($dir);
			foreach ($objects as $object)
			{
				if ($object != "." && $object != "..")
				{
					if (filetype($dir . "/" . $object) == "dir")
					{
						rrmdir($dir . "/" . $object);
					} //filetype($dir . "/" . $object) == "dir"
					else
					{
						unlink($dir . "/" . $object);
					}
				} //$object != "." && $object != ".."
			} //$objects as $object
			reset($objects);
			rmdir($dir);
			$msg = drupal_set_message("Directory deleted successfully");
			return $msg;
		} //is_dir($dir)
		$msg = drupal_set_message("Directory not present");
		return $msg;
	} //$proposal_data->id == $prop_id
	else
	{
		$msg = drupal_set_message("Data not found");
		return $msg;
	}
}
function rrmdir($dir)
{
	if (is_dir($dir))
	{
		$objects = scandir($dir);
		foreach ($objects as $object)
		{
			if ($object != "." && $object != "..")
			{
				if (filetype($dir . "/" . $object) == "dir")
					rrmdir($dir . "/" . $object);
				else
					unlink($dir . "/" . $object);
			} //$object != "." && $object != ".."
		} //$objects as $object
		reset($objects);
		rmdir($dir);
	} //is_dir($dir)
}